/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerrainRouteImport } from './routes/terrain'
import { Route as LignesRouteImport } from './routes/lignes'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'

const TerrainRoute = TerrainRouteImport.update({
  id: '/terrain',
  path: '/terrain',
  getParentRoute: () => rootRouteImport,
} as any)
const LignesRoute = LignesRouteImport.update({
  id: '/lignes',
  path: '/lignes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/lignes': typeof LignesRoute
  '/terrain': typeof TerrainRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/lignes': typeof LignesRoute
  '/terrain': typeof TerrainRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/lignes': typeof LignesRoute
  '/terrain': typeof TerrainRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contact' | '/lignes' | '/terrain'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contact' | '/lignes' | '/terrain'
  id: '__root__' | '/' | '/contact' | '/lignes' | '/terrain'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  LignesRoute: typeof LignesRoute
  TerrainRoute: typeof TerrainRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terrain': {
      id: '/terrain'
      path: '/terrain'
      fullPath: '/terrain'
      preLoaderRoute: typeof TerrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lignes': {
      id: '/lignes'
      path: '/lignes'
      fullPath: '/lignes'
      preLoaderRoute: typeof LignesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  LignesRoute: LignesRoute,
  TerrainRoute: TerrainRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
